[package]
name = "malicious_drain"   
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.29.0"

[features]
idl-build = ["anchor-lang/idl-build"]
